---
ID: "4cb5ad25-eb72-45f2-a98b-b08d824576b2"
Parent: "94a8c8e9-690b-4e65-98e7-f95800222767"
Template: "94a8c8e9-690b-4e65-98e7-f95800222767"
Path: /sitecore/templates/Project/CAR/Page Types/Article/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{E99FBF20-515B-475B-9F79-7ECE0DB1C022}">
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{FE3E37C8-AE37-4B36-B048-630ECEFE0D69}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="header"
          uid="{8BB9D970-5CF6-47E3-A68F-EF10FFF8B6B0}" />
        <r
          ds="{FA936BD6-A60E-4748-BED8-E53CD8168CA8}"
          id="{EF8A228D-EFD8-4467-BBC2-508BBAC1FBC7}"
          par=""
          ph="header"
          uid="{EB25543E-EAB8-4455-B070-F3C0195F09C9}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04f82419-1706-4f2a-8e62-22294a0a9221"
      Hint: ShowInNavigation
      Type: Checkbox
      Value: 1
    - ID: "1f5b8fc6-7441-478a-9426-a247d0d06971"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170516T160104Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: $name
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: $name
    - ID: "caa02a19-2fe7-4295-b63d-ea7a989e6be9"
      Hint: ShowChildren
      Type: Checkbox
      Value: 1
